export const marqueeTexts: string[][] = [
  [
    "Storybook",
    "React",
    "Redux",
    "React Native",
    "Expo",
    "NativeBase",
    "PWA's",
    "NextJS",
    "NextAuth",
    "SSR/SSG",
    "ISR",
    "Tailwind",
    "Angular",
    "MUI",
    "Material Design",
    "SOLID",
    "DRY",
    "KPIs",
    "Pimcore",
    "Web Components",
    "Vite",
    "Adobe Target",
    "A/B Testing",
  ],
  [
    "Typescript",
    "UI/UX",
    "RxJS",
    "NodeJS/Express",
    "Responsive",
    "Atomic Design",
    "FaunaDB",
    "Shopify",
    "GraphQL",
    "Serverless",
    "Cloud",
    "Lambda",
    "AWS",
    "Saas",
    "DynamoDB/Dynamoose",
    "NoSQL",
    "Debugging",
    "Heroku",
    "Github Packages",
    "Git",
    "Linux",
  ],
  [
    "Lerna",
    "Rollup",
    "Monorepo",
    "Turbopack",
    "Vercel",
    "Netlify",
    "Azure",
    "Yarn",
    "NPM",
    "Preact",
    "DevOps",
    "MySQL",
    "MariaDB",
    "Docker",
    "Fetchmock",
    "Postman",
    "Insomnia",
    "Swagger",
    "Photoshop",
    "Lightroom",
    "Sonar Cube",
    "Sentry",
  ],
  [
    "Figma",
    "AdobeXD",
    "Justinmind",
    "Notion",
    "PNPM",
    "Pure JS",
    "HTML",
    "SCSS",
    "CSS3",
    "UIKit",
    "Twig",
    "Bootstrap",
    "MJML",
    "Ruby",
    "C#",
    "PHP",
    "Command Line",
    "YAML",
    "JSON",
    "Agile",
    "Scrum",
  ],
  [
    "APIs",
    "Android Studio",
    "XCode Simulator",
    "Flipper",
    "Firebase",
    "Cypress",
    "Jest",
    "Auth0",
    "Miro",
    "Zod",
    "JWT",
    "Stripe",
    "ESlint",
    "Prettier",
    "Husky",
    "Docker",
    "Apollo",
    "Axios",
    "Formik",
    "Confluence",
    "Github",
    "Bitbucket",
    "Jenkins",
  ],
];

export const marqueeColors: string[] = [
  "#ffffff",
  "#1795FF",
  "#90D6FC",
  "#45C2A7",
  "#D7D7A0",
  "#4C91D0",
  "#cccccc",
  "#bc8670",
  "#e3c042",
  "#b463b5",
];