export interface ProjectPeople {
  id: string;
  projects_id: string;
  people_id: string;
  role: string;
}

export const PEOPLE_DATA: ProjectPeople[] = [
  {
    id: "1",
    projects_id: "1",
    people_id: "1",
    role: "CMS Development and Updates, UIE, CMS Functionality (Parts), Testing",
  },
  {
    id: "2",
    projects_id: "1",
    people_id: "4",
    role: "Evoluted - Everything Else",
  },
  {
    id: "3",
    projects_id: "2",
    people_id: "1",
    role: "Graphics Work, Build (Parts), CMS, Content Addition, Browser Compatibility, Functionality, Friendly URLs, Images Manipulation, Testing, Dynamic Content",
  },
  {
    id: "4",
    projects_id: "2",
    people_id: "4",
    role: "Evoluted - Design",
  },
  {
    id: "5",
    projects_id: "2",
    people_id: "6",
    role: "PSD2HTML - Original Build",
  },
  {
    id: "6",
    projects_id: "3",
    people_id: "1",
    role: "Graphics Work, Build, UIE, Form Validation (CSV/SSV) Email Script",
  },
  {
    id: "7",
    projects_id: "3",
    people_id: "4",
    role: "Evoluted - Design",
  },
  {
    id: "8",
    projects_id: "4",
    people_id: "1",
    role: "Graphics Work, Addition of Content (Parts); Stock Photography Selection, Slideshow (Homepage), Build (Parts), Browser Compatibility, CMS Development",
  },
  {
    id: "9",
    projects_id: "4",
    people_id: "4",
    role: "Evoluted - Everything Else",
  },
  {
    id: "10",
    projects_id: "5",
    people_id: "1",
    role: "Graphics Work, Addition of Content (Parts), Stock Photography Selection, Slideshow (Homepage), Build (Parts), Browser Compatibility, CMS Development",
  },
  {
    id: "11",
    projects_id: "5",
    people_id: "4",
    role: "Evoluted - Everything Else",
  },
  {
    id: "12",
    projects_id: "6",
    people_id: "1",
    role: "Graphics Work, Original Holding Page Build (Not the new website)",
  },
  {
    id: "13",
    projects_id: "6",
    people_id: "4",
    role: "Evoluted - Design",
  },
  {
    id: "14",
    projects_id: "7",
    people_id: "1",
    role: "Graphics Work, RSS Twitter Feed (Using Magpie), Browser Compatibility, CMS (Updates), Image Manipulation",
  },
  {
    id: "15",
    projects_id: "7",
    people_id: "4",
    role: "Evoluted - Everything Else",
  },
  {
    id: "16",
    projects_id: "8",
    people_id: "1",
    role: "Graphics Work, Multibyte Character Support (Charset GB 2312), User Login (Parts), Session and Token Management/Expiry, Browser Compatibility, Dynamic Content (Parts)",
  },
  {
    id: "17",
    projects_id: "8",
    people_id: "4",
    role: "Evoluted - Everything Else",
  },
  {
    id: "18",
    projects_id: "9",
    people_id: "1",
    role: "Edits to the Flash (FLV) Header",
  },
  {
    id: "19",
    projects_id: "9",
    people_id: "4",
    role: "Evoluted - Design, Functionality",
  },
  {
    id: "20",
    projects_id: "10",
    people_id: "1",
    role: "Graphics Work, Build (Parts), Localisation, CMS, HTML/CSS Validation, Testing, Content Addition, Image Manipulation",
  },
  {
    id: "21",
    projects_id: "10",
    people_id: "4",
    role: "Evoluted - Design",
  },
  {
    id: "22",
    projects_id: "11",
    people_id: "1",
    role: "Build, Adaption of tags for Constant Contact (Email mechanism), Email Client Compatibility, HTML/CSS Validation, Testing",
  },
  {
    id: "23",
    projects_id: "11",
    people_id: "4",
    role: "Evoluted - Design",
  },
  {
    id: "24",
    projects_id: "12",
    people_id: "1",
    role: "SagePay Integration and Checkout Process (Parts)",
  },
  {
    id: "25",
    projects_id: "12",
    people_id: "4",
    role: "Evoluted - Everything Else",
  },
  {
    id: "26",
    projects_id: "13",
    people_id: "1",
    role: "WordPress Installation and Setup, Theme Customisation (to fit design of the customer) Browser Compatibility, Testing",
  },
  {
    id: "27",
    projects_id: "13",
    people_id: "4",
    role: "Evoluted - Original Design",
  },
  {
    id: "28",
    projects_id: "14",
    people_id: "1",
    role: "Build, MVC Structure, Cryptography, User Login Mechanism, Document Upload and Management, Browser Compatibility, Testing",
  },
  {
    id: "29",
    projects_id: "14",
    people_id: "5",
    role: "Other - Original Design",
  },
  {
    id: "30",
    projects_id: "15",
    people_id: "1",
    role: "Graphics Work, Build (Product Detail Page, Homepage), CMS (Products Section), Browser Compatibility (Parts), Functionality (Parts), Integration with FPDF (Create PDFs Dynamically)",
  },
  {
    id: "31",
    projects_id: "15",
    people_id: "4",
    role: "Evoluted - Design",
  },
  {
    id: "32",
    projects_id: "16",
    people_id: "1",
    role: "Graphics Work, Build, CMS, MVC Structure, Content Addition, Browser Compatibility, Functionality, Friendly URLs, Images Manipulation, Multiple Site Support, Testing",
  },
  {
    id: "33",
    projects_id: "16",
    people_id: "5",
    role: "Other - Design",
  },
  {
    id: "34",
    projects_id: "17",
    people_id: "1",
    role: "Graphics Work, Build, CMS, MVC Structure, Content Addition, Browser Compatibility, Functionality, Friendly URLs, Images Manipulation, Multiple Site Support, Testing",
  },
  {
    id: "35",
    projects_id: "17",
    people_id: "5",
    role: "Other - Design",
  },
  {
    id: "36",
    projects_id: "18",
    people_id: "1",
    role: "Graphics Work, Build, CMS, MVC Structure, Content Addition, Browser Compatibility, Functionality, Friendly URLs, Images Manipulation, Multiple Site Support, Testing",
  },
  {
    id: "37",
    projects_id: "18",
    people_id: "5",
    role: "Other - Design",
  },
  {
    id: "38",
    projects_id: "19",
    people_id: "1",
    role: "Graphics Manipulation (Various), Build (Parts), CMS, Content Addition, Browser Compatibility, Functionality, Friendly URLs, Images Manipulation, Issuu API Integration, Maintenance, Testing, Document Upload and Management",
  },
  {
    id: "39",
    projects_id: "19",
    people_id: "4",
    role: "Evoluted - Design",
  },
  {
    id: "40",
    projects_id: "19",
    people_id: "6",
    role: "PSD2HTML - Initial Build",
  },
  {
    id: "41",
    projects_id: "20",
    people_id: "1",
    role: "Targetted SEO (mainly homepage), Validation and Browser Compatibility, Image Manipulation (some)",
  },
  {
    id: "42",
    projects_id: "20",
    people_id: "4",
    role: "Evoluted - Design and everything else",
  },
  {
    id: "43",
    projects_id: "21",
    people_id: "1",
    role: "CMS and everything else, except the design",
  },
  {
    id: "44",
    projects_id: "21",
    people_id: "4",
    role: "Evoluted - Design",
  },
  {
    id: "45",
    projects_id: "22",
    people_id: "1",
    role: "Email-friendly HTML Build (parts), Preparation for DotMailer",
  },
  {
    id: "46",
    projects_id: "22",
    people_id: "4",
    role: "Evoluted - Design and Build",
  },
  {
    id: "47",
    projects_id: "23",
    people_id: "1",
    role: "CMS and build of umbrella website and CMS",
  },
  {
    id: "48",
    projects_id: "23",
    people_id: "4",
    role: "Evoluted - Design and Build",
  },
  {
    id: "49",
    projects_id: "24",
    people_id: "1",
    role: "CMS and build of umbrella website and CMS",
  },
  {
    id: "50",
    projects_id: "24",
    people_id: "4",
    role: "Evoluted - Design and Build",
  },
  {
    id: "51",
    projects_id: "25",
    people_id: "1",
    role: "CMS and build of sister websites and CMS",
  },
  {
    id: "52",
    projects_id: "25",
    people_id: "4",
    role: "Evoluted - Design and Build",
  },
  {
    id: "53",
    projects_id: "26",
    people_id: "1",
    role: "Work in conjunction with Save On and GK Group websites",
  },
  {
    id: "54",
    projects_id: "26",
    people_id: "4",
    role: "Evoluted - Design and Initial Build and Various Other",
  },
  {
    id: "55",
    projects_id: "27",
    people_id: "1",
    role: "Build, Web Development, CMS",
  },
  {
    id: "56",
    projects_id: "27",
    people_id: "4",
    role: "Evoluted - Design",
  },
  {
    id: "57",
    projects_id: "28",
    people_id: "1",
    role: "Build, Web Development, CMS",
  },
  {
    id: "58",
    projects_id: "28",
    people_id: "4",
    role: "Evoluted - Design",
  },
  {
    id: "59",
    projects_id: "29",
    people_id: "1",
    role: "Build, Web Development, CMS",
  },
  {
    id: "60",
    projects_id: "29",
    people_id: "4",
    role: "Evoluted - Design",
  },
  {
    id: "61",
    projects_id: "30",
    people_id: "1",
    role: "Website Build, CMS, Testing.",
  },
  {
    id: "62",
    projects_id: "30",
    people_id: "4",
    role: "Website Design",
  },
  {
    id: "63",
    projects_id: "31",
    people_id: "1",
    role: "Build, Photography, Database Design and Development, Dynamic Content, Haversine Calculations, Content Population",
  },
  {
    id: "64",
    projects_id: "31",
    people_id: "2",
    role: "Matthew - Design, Photography (Some), Build, Image Manipulation, Graphics, Content Population",
  },
  {
    id: "65",
    projects_id: "31",
    people_id: "3",
    role: "Richard - JavaScript, Database Development, User Interface Engineering (Some)",
  },
  {
    id: "66",
    projects_id: "32",
    people_id: "1",
    role: "Build, Database Design, CMS, Dynamic Content, Content Population, Proof Reading",
  },
  {
    id: "67",
    projects_id: "32",
    people_id: "2",
    role: "Matthew - Design, Build, Content Population, Image Sourcing",
  },
  {
    id: "68",
    projects_id: "33",
    people_id: "1",
    role: "Contact Form",
  },
  {
    id: "69",
    projects_id: "33",
    people_id: "2",
    role: "Matthew - Design, Build, Content Population, Proof Reading",
  },
  {
    id: "70",
    projects_id: "33",
    people_id: "7",
    role: "Vicky - Proof Reading, Copywriting",
  },
  {
    id: "71",
    projects_id: "34",
    people_id: "1",
    role: "Database Design, CMS, Dynamic Content, Content Population, Proof Reading",
  },
  {
    id: "72",
    projects_id: "34",
    people_id: "2",
    role: "Matthew - Design, Build, Content Population, Proof Reading",
  },
  {
    id: "73",
    projects_id: "35",
    people_id: "1",
    role: "Database Design, CMS, Dynamic Content, Content Population, Proof Reading",
  },
  {
    id: "74",
    projects_id: "35",
    people_id: "2",
    role: "Matthew - Design, Build, Content Population, Proof Reading",
  },
  {
    id: "75",
    projects_id: "36",
    people_id: "1",
    role: "Database Design, Dynamic Content, User Interaction",
  },
  {
    id: "76",
    projects_id: "36",
    people_id: "2",
    role: "Matthew - Build",
  },
  {
    id: "77",
    projects_id: "36",
    people_id: "8",
    role: "David - Design",
  },
  {
    id: "78",
    projects_id: "37",
    people_id: "1",
    role: "CMS, Database Design, Dynamic Content, Content Population (Some)",
  },
  {
    id: "79",
    projects_id: "37",
    people_id: "2",
    role: "Matthew - Design, Build, Dynamic Content, Maintenance, Content Population (Some)",
  },
  {
    id: "80",
    projects_id: "38",
    people_id: "1",
    role: "Database Design, Dynamic Content, CMS, Content Population, User Interaction, Information Exchange",
  },
  {
    id: "81",
    projects_id: "38",
    people_id: "2",
    role: "Matthew - Design, Build",
  },
  {
    id: "82",
    projects_id: "39",
    people_id: "1",
    role: "Build, Content Sourcing",
  },
  {
    id: "83",
    projects_id: "39",
    people_id: "2",
    role: "Matthew - Design, Build",
  },
  {
    id: "84",
    projects_id: "40",
    people_id: "1",
    role: "Slideshow",
  },
  {
    id: "85",
    projects_id: "40",
    people_id: "2",
    role: "Matthew - Build, Content Manipulation, Browser Compatibility",
  },
  {
    id: "86",
    projects_id: "40",
    people_id: "5",
    role: "Unknown - Design",
  },
  {
    id: "87",
    projects_id: "41",
    people_id: "1",
    role: "CMS Deployment, Content Population, Widgets, Browser Compatibility, Maintenance",
  },
  {
    id: "88",
    projects_id: "41",
    people_id: "2",
    role: "Matthew - Design, Build, Image Manipulation, CMS Deployment, Content Population, Browser Compatibility",
  },
  {
    id: "89",
    projects_id: "42",
    people_id: "1",
    role: "CMS Deployment, Content Population",
  },
  {
    id: "90",
    projects_id: "42",
    people_id: "2",
    role: "Matthew - Design, Build, Image Manipulation, CMS Deployment, Content Population, Publishing",
  },
  {
    id: "91",
    projects_id: "43",
    people_id: "1",
    role: "Video Editing, CMS Deployment, Image Manipulation",
  },
  {
    id: "92",
    projects_id: "43",
    people_id: "2",
    role: "Matthew - Design, Build, Image Manipulation, CMS Deployment, Content Population, Publishing",
  },
  {
    id: "93",
    projects_id: "44",
    people_id: "1",
    role: "CMS Deployment, Widgets, Maintenance, Copywriting",
  },
  {
    id: "94",
    projects_id: "44",
    people_id: "2",
    role: "Matthew - Design, Build",
  },
  {
    id: "95",
    projects_id: "45",
    people_id: "1",
    role: "Image Manipulation, CMS Deployment, Widgets, Some Content Population, Development, Publishing, Maintenance",
  },
  {
    id: "96",
    projects_id: "45",
    people_id: "2",
    role: "Matthew - Design, Build, Image Manipulation, CMS Deployment, Content Population, Widgets, Development, Publishing",
  },
  {
    id: "97",
    projects_id: "46",
    people_id: "1",
    role: "Build, Image Manipulation, CMS Deployment, Widgets, Some Content Population, Development, Publishing, Maintenance",
  },
  {
    id: "98",
    projects_id: "46",
    people_id: "2",
    role: "Matthew - Design, Build",
  },
  {
    id: "99",
    projects_id: "47",
    people_id: "1",
    role: "Build, Image Manipulation, CMS Deployment, Widgets, Content Population, Development, Publishing",
  },
  {
    id: "100",
    projects_id: "47",
    people_id: "2",
    role: "Matthew - Design, Build, Publishing",
  },
  {
    id: "101",
    projects_id: "48",
    people_id: "1",
    role: "Build, Image Manipulation, CMS Deployment, Widgets, Content Population, Development, Publishing, Updates and Maintenance",
  },
  {
    id: "102",
    projects_id: "48",
    people_id: "2",
    role: "Matthew - Build",
  },
  {
    id: "103",
    projects_id: "48",
    people_id: "9",
    role: "Diversity Group - Design",
  },
  {
    id: "104",
    projects_id: "49",
    people_id: "1",
    role: "Instant Quote Form, Development, Publishing",
  },
  {
    id: "105",
    projects_id: "49",
    people_id: "2",
    role: "Matthew - Original Design, Build",
  },
  {
    id: "106",
    projects_id: "49",
    people_id: "3",
    role: "Richard - Google Maps API, User Interface Engineering",
  },
  {
    id: "107",
    projects_id: "50",
    people_id: "1",
    role: "Localisation API, Database Design, Content Population, Development, Information Exchange",
  },
  {
    id: "108",
    projects_id: "50",
    people_id: "2",
    role: "Matthew - Design, Build, Localisation API",
  },
  {
    id: "109",
    projects_id: "50",
    people_id: "3",
    role: "Richard - Localisation API, Database Design, User Interface Engineering, Database Development, AJAX Support, JavaScript",
  },
  {
    id: "110",
    projects_id: "50",
    people_id: "9",
    role: "Global Key Translations - Content Translations",
  },
  {
    id: "111",
    projects_id: "51",
    people_id: "1",
    role: "Build, CMS Creation, User Interaction, User Interface Engineering, Database Design, Content Population, Development, Publishing, Information Exchange",
  },
  {
    id: "112",
    projects_id: "51",
    people_id: "2",
    role: "Matthew - Design, Build",
  },
  {
    id: "113",
    projects_id: "51",
    people_id: "3",
    role: "Richard - MySQL Consultancy, Database Development, AJAX Support, User Interface Engineering",
  },
  {
    id: "114",
    projects_id: "52",
    people_id: "1",
    role: "Design, Build, CMS Deployment, Some Content Population, Development, Widgets, Publishing",
  },
  {
    id: "115",
    projects_id: "53",
    people_id: "1",
    role: "Domain and Email Management",
  },
  {
    id: "116",
    projects_id: "53",
    people_id: "2",
    role: "Matthew - Design, Build",
  },
  {
    id: "117",
    projects_id: "54",
    people_id: "1",
    role: "CMS Deployment, Content Population, Development",
  },
  {
    id: "118",
    projects_id: "54",
    people_id: "2",
    role: "Matthew - Design, CMS Deployment, Build, Content Population, Development",
  },
  {
    id: "119",
    projects_id: "54",
    people_id: "3",
    role: "Richard - Basic SEO",
  },
  {
    id: "120",
    projects_id: "55",
    people_id: "1",
    role: "CMS Deployment, Content Population, Development, Newsletters, Checkout Process, Widgets, Information Manipulation",
  },
  {
    id: "121",
    projects_id: "55",
    people_id: "2",
    role: "Matthew - Design, Build, Content Population, Product Addition, Payment Gateway, Development, Newsletters",
  },
  {
    id: "122",
    projects_id: "55",
    people_id: "3",
    role: "Richard - Checkout Streamlining",
  },
  {
    id: "123",
    projects_id: "56",
    people_id: "1",
    role: "CMS Deployment, Content Population, Development",
  },
  {
    id: "124",
    projects_id: "56",
    people_id: "2",
    role: "Matthew - Design, Build, Content Population, Development",
  },
  {
    id: "125",
    projects_id: "57",
    people_id: "1",
    role: "General Development of minor tasks",
  },
  {
    id: "126",
    projects_id: "57",
    people_id: "2",
    role: "Matthew - Original Design, Build, Content Population, Development",
  },
  {
    id: "127",
    projects_id: "58",
    people_id: "1",
    role: "CMS Deployment, Content Population, Development",
  },
  {
    id: "128",
    projects_id: "58",
    people_id: "2",
    role: "Matthew - Design, Build, Content Population, Development",
  },
  {
    id: "129",
    projects_id: "59",
    people_id: "1",
    role: "Content Population, Development, Friendly URLs",
  },
  {
    id: "130",
    projects_id: "59",
    people_id: "2",
    role: "Matthew - Build, Content Population, Development",
  },
  {
    id: "131",
    projects_id: "59",
    people_id: "3",
    role: "Richard - Build, User Interaction, Slideshow, Development",
  },
  {
    id: "132",
    projects_id: "59",
    people_id: "9",
    role: "Ryan - Design",
  },
  {
    id: "133",
    projects_id: "60",
    people_id: "1",
    role: "CMS Deployment, Content Population, Basic SEO",
  },
  {
    id: "134",
    projects_id: "60",
    people_id: "2",
    role: "Matthew - Design, Build, Content Population",
  },
  {
    id: "135",
    projects_id: "61",
    people_id: "1",
    role: "Web Graphics, Build, CMS Deployment, Image Processing, Content Population",
  },
  {
    id: "136",
    projects_id: "61",
    people_id: "9",
    role: "Unknown - Photography, Logo Design",
  },
  {
    id: "137",
    projects_id: "61",
    people_id: "10",
    role: "Jade - Modelling, Content",
  },
  {
    id: "138",
    projects_id: "62",
    people_id: "1",
    role: "Build, Friendly URLs, Shopping Cart, Content Population, Original Copy and Copywriting, SEO, Checkout and Invoicing, Dynamic Content",
  },
  {
    id: "139",
    projects_id: "62",
    people_id: "2",
    role: "Matthew - Design, Build, Content Population, Copywriting",
  },
  {
    id: "140",
    projects_id: "62",
    people_id: "3",
    role: "Richard - Build, Browser Compatibility, Development, SEO",
  },
  {
    id: "141",
    projects_id: "63",
    people_id: "1",
    role: "CMS Deployment, Video Conversion, Content Population, Development",
  },
  {
    id: "142",
    projects_id: "63",
    people_id: "2",
    role: "Matthew - Design, Build, Content Population, Development, CMS Deployment",
  },
  {
    id: "143",
    projects_id: "64",
    people_id: "1",
    role: "Friendly URLs",
  },
  {
    id: "144",
    projects_id: "64",
    people_id: "2",
    role: "Matthew - Design, Build, Graphics",
  },
  {
    id: "145",
    projects_id: "64",
    people_id: "3",
    role: "Richard - Build, Browser Compatibility, SEO, Localisation",
  },
  {
    id: "146",
    projects_id: "65",
    people_id: "1",
    role: "CMS Deployment, Development, Content Population, UI, Checkout Development, Addition of Products to Shop",
  },
  {
    id: "147",
    projects_id: "65",
    people_id: "2",
    role: "Matthew - Design, Graphics Work, Build, Development, Content Population, UI, Project Management, Checkout Development, Addition of Products to Shop, Email Campaigns",
  },
  {
    id: "148",
    projects_id: "65",
    people_id: "3",
    role: "Richard - SEO",
  },
  {
    id: "149",
    projects_id: "65",
    people_id: "7",
    role: "Vicky - Proof Reading, Copywriting",
  },
  {
    id: "150",
    projects_id: "66",
    people_id: "1",
    role: "Build, Development, Image Manipulation, Maintenance and Updates, Publishing",
  },
  {
    id: "151",
    projects_id: "66",
    people_id: "9",
    role: "Livia - Design, Photography",
  },
  {
    id: "152",
    projects_id: "67",
    people_id: "1",
    role: "CMS, Build, Web Development",
  },
  {
    id: "153",
    projects_id: "67",
    people_id: "9",
    role: "Livia - Design, Photography",
  },
  {
    id: "154",
    projects_id: "68",
    people_id: "1",
    role: "CMS, Build, Web Development",
  },
  {
    id: "155",
    projects_id: "68",
    people_id: "9",
    role: "Livia - Design, Photography",
  },
  {
    id: "156",
    projects_id: "69",
    people_id: "1",
    role: "Entire Website",
  },
  {
    id: "157",
    projects_id: "71",
    people_id: "1",
    role: "Entire Website",
  },
  {
    id: "158",
    projects_id: "72",
    people_id: "1",
    role: "Entire Website",
  },
  {
    id: "159",
    projects_id: "73",
    people_id: "1",
    role: "Entire Website",
  },
  {
    id: "160",
    projects_id: "74",
    people_id: "1",
    role: "Build, Web Development, CMS, Client Meetings, Site Visits",
  },
  {
    id: "161",
    projects_id: "74",
    people_id: "11",
    role: "HTA - Everything Else",
  },
  {
    id: "162",
    projects_id: "75",
    people_id: "1",
    role: "Website Build, CMS, Client Meetings & Site Visits, Project Management.",
  },
  {
    id: "163",
    projects_id: "75",
    people_id: "11",
    role: "Website Design, Project Management",
  },
  {
    id: "164",
    projects_id: "86",
    people_id: "1",
    role: "Website Build",
  },
  {
    id: "165",
    projects_id: "86",
    people_id: "11",
    role: "Other",
  },
  {
    id: "166",
    projects_id: "81",
    people_id: "1",
    role: "Website Build",
  },
  {
    id: "168",
    projects_id: "81",
    people_id: "11",
    role: "Website Design, Project Management",
  },
  {
    id: "169",
    projects_id: "79",
    people_id: "1",
    role: "Website Build, CMS, Internal Collaboration, Design (some), Image Manipulation",
  },
  {
    id: "170",
    projects_id: "79",
    people_id: "11",
    role: "Content, Images, Design, Management, Other",
  },
  {
    id: "171",
    projects_id: "98",
    people_id: "1",
    role: "Everything (apart from some design)",
  },
  {
    id: "172",
    projects_id: "78",
    people_id: "1",
    role: "Website Updates (some)",
  },
  {
    id: "173",
    projects_id: "78",
    people_id: "11",
    role: "Everything Else",
  },
  {
    id: "174",
    projects_id: "80",
    people_id: "1",
    role: "Website Build, CMS, Internal Collaboration, Client Interaction",
  },
  {
    id: "175",
    projects_id: "80",
    people_id: "11",
    role: "Website Design, Project Management",
  },
  {
    id: "176",
    projects_id: "91",
    people_id: "1",
    role: "Everything",
  },
  {
    id: "177",
    projects_id: "84",
    people_id: "1",
    role: "Website Build, Website Design, CMS, Internal Collaboration, Client Interaction",
  },
  {
    id: "178",
    projects_id: "84",
    people_id: "9",
    role: "Content",
  },
  {
    id: "179",
    projects_id: "93",
    people_id: "1",
    role: "Website Build",
  },
  {
    id: "180",
    projects_id: "93",
    people_id: "11",
    role: "Everything Else",
  },
  {
    id: "181",
    projects_id: "92",
    people_id: "1",
    role: "Everything",
  },
  {
    id: "182",
    projects_id: "87",
    people_id: "1",
    role: "Photographer",
  },
  {
    id: "183",
    projects_id: "83",
    people_id: "1",
    role: "Website Build, Website Design, CMS",
  },
  {
    id: "184",
    projects_id: "83",
    people_id: "9",
    role: "Content (Andrea)",
  },
  {
    id: "185",
    projects_id: "89",
    people_id: "1",
    role: "Everything",
  },
  {
    id: "186",
    projects_id: "88",
    people_id: "1",
    role: "Everything",
  },
  {
    id: "187",
    projects_id: "95",
    people_id: "1",
    role: "Photographer",
  },
  {
    id: "188",
    projects_id: "96",
    people_id: "1",
    role: "Photographer",
  },
  {
    id: "189",
    projects_id: "94",
    people_id: "1",
    role: "Website Build",
  },
  {
    id: "190",
    projects_id: "94",
    people_id: "11",
    role: "Everything Else",
  },
  {
    id: "191",
    projects_id: "90",
    people_id: "1",
    role: "Everything",
  },
  {
    id: "192",
    projects_id: "97",
    people_id: "1",
    role: "Photographer",
  },
  {
    id: "193",
    projects_id: "76",
    people_id: "1",
    role: "Website Build, Website Design (some), CMS, Client Meetings & Site Visits, Project Management, Image Manipulation",
  },
  {
    id: "194",
    projects_id: "76",
    people_id: "11",
    role: "Everything Else",
  },
  {
    id: "195",
    projects_id: "77",
    people_id: "1",
    role: "Website Build, CMS, Internal Collaboration, Client Interaction",
  },
  {
    id: "196",
    projects_id: "77",
    people_id: "11",
    role: "Everything Else",
  },
];
